name = "docgeny"
main = ".output/server/index.mjs"
account_id = "7a9f8df3353033ce3233c4d41ab4a6ff"
workers_dev = true
compatibility_date = "2022-11-07"
node_compat = true

[site]
bucket = ".output/public"

[[ d1_databases ]]
binding = "DB"
database_name = "docgeny"
database_id = "e474acb3-f48a-4ced-a796-7f0777721f4c"

[ai]
binding = "AI" # i.e. available in your Worker on env.AI